using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Zerobot.CommandCenter
{
    /// <summary>
    ///  A simple representation of all possible command tokens, generated by a lexer.
    /// </summary>
    public enum CommandToken : byte
    {
        Move,
        Stop,
        Speed,

        MarkerDown,
        MarkerUp,
    }

    /// <summary>
    /// Represents a token expression, generated by the lexer. For example:
    /// 
    /// Using the Move token with the operands up and 4
    /// 
    /// TokenExpression(Move, [up, 4]);
    /// TokenExpression.ToString() = Move up 4 
    /// 
    /// Operands before the CommandToken will be ignored
    /// </summary>
    public class TokenExpression
    {
        private readonly CommandToken token;
        private readonly List<string> operands;

        public TokenExpression(CommandToken token, List<string> operands)
        {
            this.token = token;
            this.operands = operands;
        }

        public TokenExpression(string expression)
        {
            var words = expression.Split(" ");
            if (words.Length < 2)
            {
                throw new ArgumentException("Invalid Token Expression.");
            }

            operands = new List<string>();
            bool tokenFound = false;
            foreach (string word in words)
            {
                if (tokenFound)
                {
                    operands.Add(word);
                    continue;
                }

                try
                {
                    token = ParseEnumName<CommandToken>(word);
                    tokenFound = true;
                }
                catch (ArgumentException)
                {
                    // ignores if it is not a CommandToken, this garantees that the CommandToken will always be the first in a expression
                }
            }

            if (!tokenFound)
            {
                throw new ArgumentException("The given expression doesn't contain a valid CommandToken");
            }
        }

        public override string ToString()
        {
            var builder = new StringBuilder();
            builder.Append(token.ToString());

            foreach (var operand in operands)
            {
                builder.Append(operand);
            }

            return builder.ToString();
        }

        /// <summary>
        /// Checks if the given string is equals to a value name inside the given Enum type. For example:
        /// 
        /// enum value: Color.Red
        /// value given: Red
        /// 
        /// In this case this method would return Color.Red
        /// </summary>
        /// <returns> The enum object </returns>
        public static T ParseEnumName<T>(string value) where T : Enum
        {
            foreach (T enumValue in Enum.GetValues(typeof(T)))
            {
                if (enumValue.ToString().Equals(value))
                {
                    return enumValue;
                }
            }

            throw new ArgumentException();
        }
    }
}
